# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.stats:
        class: AppBundle\Service\StatsService
        arguments: []

    app.survey_write:
        class:     AppBundle\Entity\Repository\Survey\SurveyWriteRepository
        arguments: ['@doctrine.orm.entity_manager']

    app.survey_read:
        class:     AppBundle\Entity\Repository\Survey\SurveyReadRepository
        arguments: ['@doctrine.orm.entity_manager']

    app.question_write:
        class:     AppBundle\Entity\Repository\Question\QuestionWriteRepository
        arguments: ['@doctrine.orm.entity_manager']

    app.question_read:
        class:     AppBundle\Entity\Repository\Question\QuestionReadRepository
        arguments: ['@doctrine.orm.entity_manager']

    app.choice_edit_command:
        class:     AppBundle\Entity\Repository\Choice\Command\EditCommand
        arguments: ['']

    app.choice_getall_query:
        class:     AppBundle\Entity\Repository\Choice\Query\GetAllQuery
        arguments: [ChoiceReadRepository]


    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
